### PR TITLE
Ensure completion listeners fire after progress listeners (fixes #20)

### LINKED ISSUE #20: Complete listener does not necessarily fire last
Hi guys,

Could you please update your addCompletionListener() to always fire last (after progress events)? 

I noticed that it is pushed into your array of progress event listeners, which does not guarantee consistent event fire order. 

Thank you,
David

### PR DESCRIPTION
**Pull request by robinnorth**

### CODE REVIEW

**Comment by joelfillmore** [comment]
@robinnorth - I merged your previous PR, can you resolve the conflicts with this one and update?

**Comment by robinnorth** [comment]
@joelfillmore - I've rebased my commits on master now, thanks for merging the previous PR. I wanted to make sure each was able to be merged separately, in case you didn't welcome a refactor 😉 . Once you've merged this, it might be worth tagging a new version and publishing a npm package update. I plan to investigate a tag-based `PxLoaderScript` plugin for JS files as part of my current project, but that might come later on...

**Comment by joelfillmore** [comment]
Thanks @robinnorth, I will publish a new npm version

**Comment by robinnorth** [comment]
Thanks @joelfillmore! Would you mind also updating the Bower package and adding a `v1.1.0` tag to the commit so Bower and npm are kept in sync?

**Comment by joelfillmore** [comment]
Yes, done!

**Comment by robinnorth** [comment]
Thanks @joelfillmore! I can't see the tag in the repo tags list though, perhaps it hasn't pushed. Bower still sees `v1.0.0` as being the latest version as a consequence.

**Comment by joelfillmore** [comment]
Took another look and realized I hadn't pushed the tags. Fixed now, thanks @robinnorth!

**Comment by robinnorth** [comment]
Nice one @joelfillmore, thanks for putting up with my persistent requests 😉  Can confirm Bower sees `v1.1.0` as the latest version now 👍 🎉

**Pull request merged**
